name: products
image:
  back: var(--color-black)
  color: var(--color-gray-500)
  cover: true
  icon: kart-store
  query: false
options:
  changeSlug: false
  changeTemplate: false
  delete: false
  duplicate: false
  move: false
buttons:
  preview: true
  sync:
    icon: refresh
    text: bnomei.kart.sync-provider
    link: '{< site.kart.urls.sync("products") >}'
  status: true
tabs:
  overview:
    sections:
      stats:
        label: bnomei.kart.summary
        type: stats
        reports:
          - 
            label: bnomei.kart.products
            value: '{{ page.children.count }}'
          - 
            label: bnomei.kart.out-of-stock
            value: '{{ page.outOfStock.count }}'
            link: '{{ site.kart.page("stocks")?.panel.url }}'
          - 
            label: bnomei.kart.provider
            value: '{{ site.kart.provider.title }}'
          - 
            label: bnomei.kart.last-sync
            value: '{{ site.kart.provider.updatedAt("products") }}'
      meta:
        type: fields
        fields:
          categories:
            label: '{{ t("bnomei.kart.categories") }} ({{ site.kart.categories.count }})'
            type: allcategories
            disabled: true
            translate: false
            width: 1/4
          tags:
            label: '{{ t("bnomei.kart.tags") }} ({{ site.kart.tags.count }})'
            type: alltags
            disabled: true
            translate: false
            width: 1/2
          variants:
            label: '{{ t("bnomei.kart.variants") }} ({{ site.kart.variants.count }})'
            type: allvariants
            disabled: true
            translate: false
            width: 1/4
          line:
            type: line
      products:
        label: bnomei.kart.products
        type: pages
        layout: cards
        search: true
        template: product
        info: '{{ page.formattedPrice }} [{{ page.stockWithVariants }}]{{ page.inStock ? "" : " ⚠️" }}{{ page.featured.ecco(" ★") }}{{ page.variants.ecco(" ❖") }}{{ page.downloads.ecco(" ↓") }}'
        image:
          cover: true
          query: page.gallery.first.toFile
        limit: 1000
        sortable: false
        sortBy: title asc
  files:
    sections:
      files:
        type: files
        info: '{{ file.dimensions }} ・ {{ file.niceSize }}'
        layout: cards
        image:
          cover: true
        limit: 1000
        search: true
        sortable: false
        sortBy: filename asc
