name: products
options:
  changeSlug: false
  changeTemplate: false
  delete: false
  duplicate: false
  move: false
buttons:
  preview: true
  sync:
    icon: refresh
    text: bnomei.kart.sync-provider
    link: '{< site.kart.urls.sync("products") >}'
  status: true
tabs:
  overview:
    sections:
      stats:
        label: bnomei.kart.summary
        type: stats
        reports:
          - 
            label: bnomei.kart.products
            value: '{{ page.children.count }}'
          - 
            label: bnomei.kart.provider
            value: '{{ site.kart.provider.title }}'
          - 
            label: bnomei.kart.last-sync
            value: '{{ site.kart.provider.updatedAt("products") }}'
      meta:
        type: fields
        fields:
          line:
            type: line
      products:
        label: bnomei.kart.products
        type: pages
        layout: cards
        search: true
        template: product
        info: '{{ page.formattedPrice }}'
        image:
          query: page.gallery.first.toFile
        limit: 1000
  files:
    sections:
      files:
        type: files
        info: '{{ file.dimensions }} ・ {{ file.niceSize }}'
        layout: cardlets
        image:
          cover: true
