name: product
num: '{{ page.created.toDate("YmdHis") }}'
options:
  changeTemplate: false
tabs:
  provider:
    label: bnomei.kart.provider-storage
    icon: globe
    sections:
      stats:
        label: bnomei.kart.summary
        type: stats
        reports:
          - 
            value: '{{ page.formattedPrice() }}'
          - 
            label: bnomei.kart.sold
            value: '{{ page.sold }}'
            link: '{{ site.kart.page("orders").url }}'
          - 
            label: bnomei.kart.stock
            value: '{{ page.stock }}'
            link: '{{ page.stockUrl }}'
      meta:
        type: fields
        fields:
          line:
            type: line
          price:
            label: bnomei.kart.price
            type: number
            min: 0
            step: 0.01
            default: 0
            after: '{{ kirby.option("bnomei.kart.currency") }}'
            width: 1/2
            translate: false
            virtual: true
          created:
            label: bnomei.kart.created
            type: date
            time: true
            default: now
            translate: false
            width: 1/2
          description:
            label: bnomei.kart.description
            type: textarea
            width: 1/2
            virtual: true
          gallery:
            label: bnomei.kart.gallery
            type: files
            query: page.parent.images
            uploads:
              parent: page.parent
              template: product-gallery
            width: 1/2
            translate: false
            virtual: true
          categories:
            label: bnomei.kart.categories
            type: tags
            translate: false
            virtual: true
          tags:
            label: bnomei.kart.tags
            type: tags
            translate: false
            virtual: true
          raw:
            type: hidden
            translate: false
            virtual: true
          _dump:
            label: bnomei.kart.raw-values
            type: info
            theme: info
            text: '{< page.dump("raw", 82) >}'
  local:
    label: bnomei.kart.local-storage
    icon: server
    extends: tabs/product
